// <auto-generated />
using BookstoreRepositoryLayer.Repository;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace BookstoreRepositoryLayer.Migrations
{
    [DbContext(typeof(UserContext))]
    [Migration("20210424182247_secondary")]
    partial class secondary
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.14-servicing-32113")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("BookstoreModelLayer.AdminRegistration", b =>
                {
                    b.Property<int>("adminId")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("email");

                    b.Property<string>("firstName");

                    b.Property<string>("lastName");

                    b.Property<string>("password");

                    b.Property<string>("phone");

                    b.HasKey("adminId");

                    b.ToTable("AdminRegister");
                });

            modelBuilder.Entity("BookstoreModelLayer.CustomerRegistration", b =>
                {
                    b.Property<long>("UserId")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("email");

                    b.Property<string>("firstName");

                    b.Property<string>("lastName");

                    b.Property<string>("password");

                    b.Property<string>("phone");

                    b.Property<string>("role");

                    b.HasKey("UserId");

                    b.ToTable("CustomerRegister");
                });

            modelBuilder.Entity("BookstoreModelLayer.LoginAdminAccount", b =>
                {
                    b.Property<string>("AdminID")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Password")
                        .IsRequired();

                    b.HasKey("AdminID");

                    b.ToTable("LoginAdmin");
                });

            modelBuilder.Entity("BookstoreModelLayer.LoginCustomerAccount", b =>
                {
                    b.Property<string>("Email")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Password")
                        .IsRequired();

                    b.HasKey("Email");

                    b.ToTable("LoginCustomer");
                });
#pragma warning restore 612, 618
        }
    }
}
